# OpenAI API key - replace with your actual key
OPENAI_API_KEY = "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"

# You can add more secrets here if needed 
###OPENAI_API_KEY ="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"